# Generated by Django 3.0.7 on 2020-08-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
