# Generated by Django 3.0.7 on 2020-08-13 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200812_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='topic',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
